insert into Person(name, job) values('Harrison', 'Engineer')
insert into Person(name, job) values('Harrison', 'Hello')
insert into Person(name, job) values('Artem', 'Gamer')
insert into Person(name, job) values('Harry', 'Unemployed')
insert into Person(name, job) values('Tolstoy', 'Writer')
insert into Post values(1, 'HelloWorld', 1)
insert into Post values(2, 'HelloWorld', 1)
insert into Post values(3, 'HelloWorld', 2)
